name = "omarchy_install"
name_pretty = "Install"
icon = "system-software-install"

[[entries]]
text = "Package"
Subtext = "Install system packages"
icon = "package"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'terminal omarchy-pkg-install'"}

[[entries]]
text = "AUR"
Subtext = "Install from Arch User Repository"
icon = "package"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'terminal omarchy-pkg-aur-install'"}

[[entries]]
text = "Web"
Subtext = "Install web applications"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-webapp-install'"}

[[entries]]
text = "TUI"
Subtext = "Install terminal user interfaces"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-tui-install'"}

[[entries]]
text = "Windows"
Subtext = "Set up Windows virtual machine"
icon = "computer"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-windows-vm install'"}

[[entries]]
text = "Dropbox"
Subtext = "Cloud storage and file sync"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dropbox'"}

[[entries]]
text = "Tailscale"
Subtext = "Secure mesh VPN network"
icon = "applications-science"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-tailscale'"}

[[entries]]
text = "Bitwarden"
Subtext = "Password manager and vault"
icon = "dialog-password"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_and_launch Bitwarden bitwarden bitwarden-cli bitwarden'"}

[[entries]]
text = "Chromium"
Subtext = "Browser with Google account sync"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-chromium-google-account'"}

[[entries]]
text = "VSCode"
Subtext = "Visual Studio Code editor"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-vscode'"}

[[entries]]
text = "Cursor"
Subtext = "AI-powered code editor"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_and_launch Cursor cursor-bin cursor'"}

[[entries]]
text = "Zed"
Subtext = "High-performance code editor"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_and_launch Zed zed dev.zed.Zed'"}

[[entries]]
text = "Sublime"
Subtext = "Sophisticated text editor"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'aur_install_and_launch Sublime Text sublime-text-4 sublime_text'"}

[[entries]]
text = "Helix"
Subtext = "Modern modal text editor"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install Helix helix'"}

[[entries]]
text = "Emacs"
Subtext = "Extensible text editor"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install Emacs emacs-wayland && systemctl --user enable --now emacs.service'"}

[[entries]]
text = "Alacritty"
Subtext = "GPU-accelerated terminal"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_terminal alacritty'"}

[[entries]]
text = "Ghostty"
Subtext = "Fast native terminal emulator"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_terminal ghostty'"}

[[entries]]
text = "Kitty"
Subtext = "Feature-rich terminal emulator"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_terminal kitty'"}

[[entries]]
text = "Claude"
Subtext = "AI coding assistant CLI"
icon = "applications-science"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install Claude Code claude-code'"}

[[entries]]
text = "Cursor"
Subtext = "AI coding assistant CLI"
icon = "applications-science"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'aur_install Cursor CLI cursor-cli'"}

[[entries]]
text = "OpenAI"
Subtext = "OpenAI Codex CLI"
icon = "applications-science"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'aur_install OpenAI Codex openai-codex-bin'"}

[[entries]]
text = "Gemini"
Subtext = "Google Gemini CLI"
icon = "applications-science"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'aur_install Gemini gemini-cli'"}

[[entries]]
text = "Studio"
Subtext = "Run LLMs locally"
icon = "applications-science"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install LM Studio lmstudio'"}

[[entries]]
text = "Ollama"
Subtext = "Local AI model runner"
icon = "applications-science"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install Ollama $ollama_pkg'"}

[[entries]]
text = "Crush"
Subtext = "AI coding assistant"
icon = "applications-science"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install Crush crush-bin'"}

[[entries]]
text = "opencode"
Subtext = "Open source code assistant"
icon = "applications-science"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install opencode opencode'"}

[[entries]]
text = "Steam"
Subtext = "Gaming platform and store"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-steam'"}

[[entries]]
text = "RetroArch"
Subtext = "Retro gaming emulator frontend"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'aur_install_and_launch RetroArch retroarch retroarch-assets libretro libretro-fbneo com.libretro.RetroArch.desktop'"}

[[entries]]
text = "Minecraft"
Subtext = "Block-building sandbox game"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'aur_install_and_launch Minecraft [AUR] minecraft-launcher minecraft-launcher'"}

[[entries]]
text = "Install Theme"
Subtext = "Install visual themes from github links"
icon = "preferences-desktop-theme"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-theme-install'"}

[[entries]]
text = "Background"
Subtext = "Set desktop wallpaper"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'nautilus ~/.config/omarchy/current/theme/backgrounds'"}

[[entries]]
text = "Meslo"
Subtext = "Meslo LG Mono Nerd Font"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_font Meslo LG Mono ttf-meslo-nerd MesloLGL Nerd Font'"}

[[entries]]
text = "Fira"
Subtext = "Fira Code Nerd Font"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_font Fira Code ttf-firacode-nerd FiraCode Nerd Font'"}

[[entries]]
text = "Victor"
Subtext = "Victor Mono Nerd Font"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_font Victor Code ttf-victor-mono-nerd VictorMono Nerd Font'"}

[[entries]]
text = "Bistream"
Subtext = "Bitstream Vera Mono Nerd Font"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_font Bistream Vera Code ttf-bitstream-vera-mono-nerd BitstromWera Nerd Font'"}

[[entries]]
text = "Rails"
Subtext = "Ruby on Rails framework"
icon = "applications-ruby"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env ruby'"}

[[entries]]
text = "Docker"
Subtext = "Container platform and databases"
icon = "container"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-docker-dbs'"}

[[entries]]
text = "Go"
Subtext = "Go programming language"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env go'"}

[[entries]]
text = "Python"
Subtext = "Python programming language"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env python'"}

[[entries]]
text = "Zig"
Subtext = "Zig programming language"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env zig'"}

[[entries]]
text = "Rust"
Subtext = "Rust programming language"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env rust'"}

[[entries]]
text = "Java"
Subtext = "Java development kit"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env java'"}

[[entries]]
text = "NET"
Subtext = ".NET development platform"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env dotnet'"}

[[entries]]
text = "OCaml"
Subtext = "OCaml programming language"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env ocaml'"}

[[entries]]
text = "Clojure"
Subtext = "Clojure programming language"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env clojure'"}

[[entries]]
text = "Node"
Subtext = "Node.js JavaScript runtime"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env node'"}

[[entries]]
text = "Bun"
Subtext = "Fast JavaScript runtime"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env bun'"}

[[entries]]
text = "Deno"
Subtext = "Secure JavaScript runtime"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env deno'"}

[[entries]]
text = "PHP"
Subtext = "PHP programming language"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env php'"}

[[entries]]
text = "Laravel"
Subtext = "Laravel PHP framework"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env laravel'"}

[[entries]]
text = "Symfony"
Subtext = "Symfony PHP framework"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env symfony'"}

[[entries]]
text = "Elixir"
Subtext = "Elixir programming language"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env elixir'"}

[[entries]]
text = "Phoenix"
Subtext = "Phoenix web framework"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env phoenix'"}