# Install
name = "omarchy_install"
name_pretty = "Install"
icon = "system-software-install"

[[entries]]
text = "Package"
Subtext = "Install"
icon = "package"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'terminal omarchy-pkg-install'"}

[[entries]]
text = "AUR"
Subtext = "Install"
icon = "package"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'terminal omarchy-pkg-aur-install'"}

[[entries]]
text = "Web"
Subtext = "Install"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-webapp-install'"}

[[entries]]
text = "TUI"
Subtext = "Install"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-tui-install'"}

[[entries]]
text = "Windows"
Subtext = "Install"
icon = "computer"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-windows-vm install'"}

[[entries]]
text = "Dropbox"
Subtext = "Install > Service"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dropbox'"}

[[entries]]
text = "Tailscale"
Subtext = "Install > Service"
icon = "applications-science"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-tailscale'"}

[[entries]]
text = "Bitwarden"
Subtext = "Install > Service"
icon = "dialog-password"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_and_launch Bitwarden bitwarden bitwarden-cli bitwarden'"}

[[entries]]
text = "Chromium"
Subtext = "Install > Service"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-chromium-google-account'"}

[[entries]]
text = "VSCode"
Subtext = "Install > Editor"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-vscode'"}

[[entries]]
text = "Cursor"
Subtext = "Install > Editor"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_and_launch Cursor cursor-bin cursor'"}

[[entries]]
text = "Zed"
Subtext = "Install > Editor"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_and_launch Zed zed dev.zed.Zed'"}

[[entries]]
text = "Sublime"
Subtext = "Install > Editor"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'aur_install_and_launch Sublime Text sublime-text-4 sublime_text'"}

[[entries]]
text = "Helix"
Subtext = "Install > Editor"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install Helix helix'"}

[[entries]]
text = "Emacs"
Subtext = "Install > Editor"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install Emacs emacs-wayland && systemctl --user enable --now emacs.service'"}

[[entries]]
text = "Alacritty"
Subtext = "Install > Terminal"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_terminal alacritty'"}

[[entries]]
text = "Ghostty"
Subtext = "Install > Terminal"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_terminal ghostty'"}

[[entries]]
text = "Kitty"
Subtext = "Install > Terminal"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_terminal kitty'"}

[[entries]]
text = "Claude"
Subtext = "Install > AI"
icon = "applications-science"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install Claude Code claude-code'"}

[[entries]]
text = "Cursor"
Subtext = "Install > AI"
icon = "applications-science"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'aur_install Cursor CLI cursor-cli'"}

[[entries]]
text = "OpenAI"
Subtext = "Install > AI"
icon = "applications-science"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'aur_install OpenAI Codex openai-codex-bin'"}

[[entries]]
text = "Gemini"
Subtext = "Install > AI"
icon = "applications-science"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'aur_install Gemini gemini-cli'"}

[[entries]]
text = "Studio"
Subtext = "Install > AI"
icon = "applications-science"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install LM Studio lmstudio'"}

[[entries]]
text = "Ollama"
Subtext = "Install > AI"
icon = "applications-science"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install Ollama $ollama_pkg'"}

[[entries]]
text = "Crush"
Subtext = "Install > AI"
icon = "applications-science"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install Crush crush-bin'"}

[[entries]]
text = "opencode"
Subtext = "Install > AI"
icon = "applications-science"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install opencode opencode'"}

[[entries]]
text = "Steam"
Subtext = "Install > Gaming"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-steam'"}

[[entries]]
text = "RetroArch"
Subtext = "Install > Gaming"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'aur_install_and_launch RetroArch retroarch retroarch-assets libretro libretro-fbneo com.libretro.RetroArch.desktop'"}

[[entries]]
text = "Minecraft"
Subtext = "Install > Gaming"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'aur_install_and_launch Minecraft [AUR] minecraft-launcher minecraft-launcher'"}

[[entries]]
text = "Theme"
Subtext = "Install > Style"
icon = "preferences-desktop-theme"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-theme-install'"}

[[entries]]
text = "Background"
Subtext = "Install > Style"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'nautilus ~/.config/omarchy/current/theme/backgrounds'"}

[[entries]]
text = "Meslo"
Subtext = "Install > Font"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_font Meslo LG Mono ttf-meslo-nerd MesloLGL Nerd Font'"}

[[entries]]
text = "Fira"
Subtext = "Install > Font"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_font Fira Code ttf-firacode-nerd FiraCode Nerd Font'"}

[[entries]]
text = "Victor"
Subtext = "Install > Font"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_font Victor Code ttf-victor-mono-nerd VictorMono Nerd Font'"}

[[entries]]
text = "Bistream"
Subtext = "Install > Font"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'install_font Bistream Vera Code ttf-bitstream-vera-mono-nerd BitstromWera Nerd Font'"}

[[entries]]
text = "Rails"
Subtext = "Install > Development"
icon = "applications-ruby"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env ruby'"}

[[entries]]
text = "Docker"
Subtext = "Install > Development"
icon = "container"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-docker-dbs'"}

[[entries]]
text = "Go"
Subtext = "Install > Development"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env go'"}

[[entries]]
text = "Python"
Subtext = "Install > Development"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env python'"}

[[entries]]
text = "Zig"
Subtext = "Install > Development"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env zig'"}

[[entries]]
text = "Rust"
Subtext = "Install > Development"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env rust'"}

[[entries]]
text = "Java"
Subtext = "Install > Development"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env java'"}

[[entries]]
text = "NET"
Subtext = "Install > Development"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env dotnet'"}

[[entries]]
text = "OCaml"
Subtext = "Install > Development"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env ocaml'"}

[[entries]]
text = "Clojure"
Subtext = "Install > Development"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env clojure'"}

[[entries]]
text = "Node"
Subtext = "Install > Javascript"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env node'"}

[[entries]]
text = "Bun"
Subtext = "Install > Javascript"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env bun'"}

[[entries]]
text = "Deno"
Subtext = "Install > Javascript"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env deno'"}

[[entries]]
text = "PHP"
Subtext = "Install > PHP"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env php'"}

[[entries]]
text = "Laravel"
Subtext = "Install > PHP"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env laravel'"}

[[entries]]
text = "Symfony"
Subtext = "Install > PHP"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env symfony'"}

[[entries]]
text = "Elixir"
Subtext = "Install > Elixir"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env elixir'"}

[[entries]]
text = "Phoenix"
Subtext = "Install > Elixir"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-install-dev-env phoenix'"}
