name = "omarchy_system"
name_pretty = "System"
icon = "system-shutdown"
action = "%VALUE%"

[[entries]]
text = "Lock"
Subtext = "Lock the screen"
icon = "system-lock-screen"
value = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'omarchy-lock-screen'"

[[entries]]
text = "Screensaver"
Subtext = "Activate screensaver"
icon = "preferences-desktop-screensaver"
value = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'omarchy-launch-screensaver force'"

[[entries]]
text = "Suspend"
Subtext = "Sleep mode to save power"
icon = "system-suspend"
value = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'systemctl suspend'"

[[entries]]
text = "Restart"
Subtext = "Reboot the system"
icon = "system-reboot"
value = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'omarchy-state clear re*-required && systemctl reboot --no-wall'"

[[entries]]
text = "Shutdown"
Subtext = "Power off the system"
icon = "system-shutdown"
value = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'omarchy-state clear re*-required && systemctl poweroff --no-wall'"