name = "omarchy_remove"
name_pretty = "Remove"
icon = "edit-delete"

[[entries]]
text = "Package"
Subtext = "Uninstall system packages"
icon = "package"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'terminal omarchy-pkg-remove'"}

[[entries]]
text = "Web"
Subtext = "Remove web applications"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-webapp-remove'"}

[[entries]]
text = "TUI"
Subtext = "Remove terminal applications"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-tui-remove'"}

[[entries]]
text = "Remove Theme"
Subtext = "Uninstall visual themes installed using github"
icon = "preferences-desktop-theme"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-theme-remove'"}

[[entries]]
text = "Windows"
Subtext = "Delete Windows virtual machine"
icon = "computer"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-windows-vm remove'"}

[[entries]]
text = "Fingerprint"
Subtext = "Remove fingerprint authentication"
icon = "input-touchpad"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-setup-fingerprint --remove'"}

[[entries]]
text = "Fido2"
Subtext = "Remove FIDO2 hardware key"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-setup-fido2 --remove'"}