# Remove
name = "omarchy_remove"
name_pretty = "Remove"
icon = "edit-delete"

[[entries]]
text = "Remove > Package"
icon = "package"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'terminal omarchy-pkg-remove'"}

[[entries]]
text = "Remove > Web"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-webapp-remove'"}

[[entries]]
text = "Remove > TUI"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-tui-remove'"}

[[entries]]
text = "Remove > Theme"
icon = "preferences-desktop-theme"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-theme-remove'"}

[[entries]]
text = "Remove > Windows"
icon = "computer"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-windows-vm remove'"}

[[entries]]
text = "Remove > Fingerprint"
icon = "input-touchpad"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-setup-fingerprint --remove'"}

[[entries]]
text = "Remove > Fido2"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'present_terminal omarchy-setup-fido2 --remove'"}
