# Trigger
name = "omarchy_trigger"
name_pretty = "Trigger"
icon = "media-record"

[[entries]]
text = "Editing"
Subtext = "Trigger > Capture > Screenshot"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'omarchy-cmd-screenshot smart'"}

[[entries]]
text = "Clipboard"
Subtext = "Trigger > Capture > Screenshot"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'omarchy-cmd-screenshot smart clipboard'"}

[[entries]]
text = "Region"
Subtext = "Trigger > Capture > Screenrecord"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'omarchy-cmd-screenrecord'"}

[[entries]]
text = "Region + Audio"
Subtext = "Trigger > Capture > Screenrecord"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'omarchy-cmd-screenrecord region --with-audio'"}

[[entries]]
text = "Display"
Subtext = "Trigger > Capture > Screenrecord"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'omarchy-cmd-screenrecord output'"}

[[entries]]
text = "Display + Audio"
Subtext = "Trigger > Capture > Screenrecord"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'omarchy-cmd-screenrecord output --with-audio'"}

[[entries]]
text = "Display + Webcam"
Subtext = "Trigger > Capture > Screenrecord"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'omarchy-cmd-screenrecord output --with-audio --with-webcam'"}

[[entries]]
text = "Color"
Subtext = "Trigger > Capture"
icon = "color-picker"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'pkill hyprpicker || hyprpicker -a'"}

[[entries]]
text = "Clipboard"
Subtext = "Trigger > Share"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'terminal bash -c omarchy-cmd-share clipboard'"}

[[entries]]
text = "File"
Subtext = "Trigger > Share"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'terminal bash -c omarchy-cmd-share file'"}

[[entries]]
text = "Folder"
Subtext = "Trigger > Share"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'terminal bash -c omarchy-cmd-share folder'"}

[[entries]]
text = "Screensaver"
Subtext = "Trigger > Toggle"
icon = "preferences-desktop-screensaver"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'omarchy-toggle-screensaver'"}

[[entries]]
text = "Nightlight"
Subtext = "Trigger > Toggle"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'omarchy-toggle-nightlight'"}

[[entries]]
text = "Idle"
Subtext = "Trigger > Toggle"
icon = "applications-other"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'omarchy-toggle-idle'"}

[[entries]]
text = "Bar"
Subtext = "Trigger > Toggle"
icon = "preferences-desktop"
actions = {"pick" = "$HOME/.local/share/omarchy/bin/omarchy-safe-exec 'omarchy-toggle-waybar'"}
